const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
    closeApp: () => ipcRenderer.invoke('app-close'),
    minimizeApp: () => ipcRenderer.invoke('app-minimize'),
    getSystemRam: () => ipcRenderer.invoke('get-system-ram'),
    killAllJava: () => ipcRenderer.invoke('kill-all-java'),
    getServers: () => ipcRenderer.invoke('get-servers'),
    createServer: (data) => ipcRenderer.invoke('create-server', data),
    deleteServer: (folder) => ipcRenderer.invoke('delete-server', folder),
    startServer: (folder) => ipcRenderer.invoke('start-server', folder),
    stopServer: (folder) => ipcRenderer.invoke('stop-server', folder),
    killServer: (folder) => ipcRenderer.invoke('kill-server', folder),
    sendCommand: (folder, cmd) => ipcRenderer.invoke('send-command', folder, cmd),
    listFiles: (folder, subpath) => ipcRenderer.invoke('list-files', folder, subpath),
    readFile: (folder, subpath) => ipcRenderer.invoke('read-file', folder, subpath),
    writeFile: (folder, subpath, data) => ipcRenderer.invoke('write-file', folder, subpath, data),
    createNewItem: (folder, subpath, itemName, isFolder) => ipcRenderer.invoke('create-new-item', folder, subpath, itemName, isFolder),
    deleteFileItem: (folder, subpath) => ipcRenderer.invoke('delete-file-item', folder, subpath),
    moveFileItem: (folder, sourceSubpath, destSubpath) => ipcRenderer.invoke('move-file-item', folder, sourceSubpath, destSubpath),
    createBackup: (folder, backupName) => ipcRenderer.invoke('create-backup', folder, backupName),
    listBackups: (folder) => ipcRenderer.invoke('list-backups', folder),
    deleteBackup: (folder, backupName) => ipcRenderer.invoke('delete-backup', folder, backupName),
    renameBackup: (folder, oldName, newName) => ipcRenderer.invoke('rename-backup', folder, oldName, newName),
    saveConfig: (folder, configData) => ipcRenderer.invoke('save-config', folder, configData),
    reorderServers: (folderOrderArray) => ipcRenderer.invoke('reorder-servers', folderOrderArray),
    resetWorld: (folder) => ipcRenderer.invoke('reset-world', folder),
    resetServer: (folder) => ipcRenderer.invoke('reset-server', folder),
    getPlayers: (folder) => ipcRenderer.invoke('get-players', folder),
    getStats: (folder) => ipcRenderer.invoke('get-stats', folder),
    checkManifestUpdates: () => ipcRenderer.invoke('check-manifest-updates'),
    hotLoadJar: (folder, url) => ipcRenderer.invoke('hot-load-jar', folder, url),
    listTasks: (folder) => ipcRenderer.invoke('list-tasks', folder),
    saveTask: (folder, task) => ipcRenderer.invoke('save-task', folder, task),
    deleteTask: (folder, taskId) => ipcRenderer.invoke('delete-task', folder, taskId),
    wipePlayerData: (folder) => ipcRenderer.invoke('wipe-player-data', folder),
    clearLogs: (folder) => ipcRenderer.invoke('clear-logs', folder),
    purgeCache: (folder) => ipcRenderer.invoke('purge-cache', folder),
    openExternal: (folder, subpath) => ipcRenderer.invoke('open-external', folder, subpath),
    onConsoleLog: (callback) => ipcRenderer.on('console-log', (e, folder, value) => callback(folder, value)),
    onServerStatus: (callback) => ipcRenderer.on('server-status', (e, folder, value, port) => callback(folder, value, port))
});